"""Added name in user model

Revision ID: 6e541ea24372
Revises: 42117ebba1e3
Create Date: 2026-06-08 23:49:19.524243

"""

import sqlalchemy as sa
import sqlmodel  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision = "6e541ea24372"
down_revision = "42117ebba1e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    )

    op.execute(
        sa.text(
            "UPDATE users "
            "SET name = COALESCE(name, split_part(email, '@', 1)) "
            "WHERE name IS NULL"
        )
    )
    op.alter_column("users", "name", nullable=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
